// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EbaPizzaria.API.Models;

public partial class Cliente
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [Required]
    [StringLength(15)]
    [Unicode(false)]
    public string Contato { get; set; }

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}