// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EbaPizzaria.API.Models;

public partial class Ingredientes
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [ForeignKey("IdIngrediente")]
    [InverseProperty("IdIngrediente")]
    public virtual ICollection<Pizza> IdPizza { get; set; } = new List<Pizza>();
}