// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EbaPizzaria.API.Models;

[PrimaryKey("IdPedido", "IdPizza")]
public partial class ItensPedido
{
    [Key]
    public int IdPedido { get; set; }

    [Key]
    public int IdPizza { get; set; }

    [Column(TypeName = "decimal(4, 2)")]
    public decimal ValorUnitario { get; set; }

    public int Quatidade { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal ValorTotal { get; set; }

    [ForeignKey("IdPedido")]
    [InverseProperty("ItensPedido")]
    public virtual Pedido IdPedidoNavigation { get; set; }

    [ForeignKey("IdPizza")]
    [InverseProperty("ItensPedido")]
    public virtual Pizza IdPizzaNavigation { get; set; }
}