// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EbaPizzaria.API.Models;

public partial class Pedido
{
    [Key]
    public int Id { get; set; }

    public int IdCliente { get; set; }

    public DateOnly DataPedido { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal ValorPedido { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("Pedido")]
    public virtual Cliente IdClienteNavigation { get; set; }

    [InverseProperty("IdPedidoNavigation")]
    public virtual ICollection<ItensPedido> ItensPedido { get; set; } = new List<ItensPedido>();
}